### ISSUE TITLE
Collaborators

### ISSUE THREAD

**Issue by sebastianbergmann** [sebastianbergmann/phpunit-documentation-brazilian-portuguese#2]
At the moment, @Gleidson2012 is the only configured collaborator for this project. Which means that only he reviews pull requests and merges them (I do not speak Portuguese and therefore do not touch the translation).

@Gleidson2012 Do you have collaborators that should be added to this project so that they, too, can review and merge pull requests?

**Comment by rafaelaffonsor** [comment]
Hey guys. I can help as well.

It's all about reviewing translations only ?

Anyway, count me in.

Cheers!

**Comment by Gleidson2012** [comment]
Hi @sebastianbergmann! 

I "recruited" until the moment only a collaborator: @rafaelaffonsor .

Welcome @rafaelaffonsor .
